// Email delivery for the attendance report (P1 6.1). Sends the report PDF as
// an attachment through the school's own SMTP server (Gmail app password,
// Office 365, or any on-prem mail server). Pure-JS nodemailer — no native
// modules, so it runs in the Electron main process and packages cleanly.
import nodemailer from 'nodemailer';
import type { Settings } from '../../shared/types';
import type { ReportData, EmailResult } from '../../shared/types';
import { exportReportToPdf } from './report-pdf';

function parseRecipients(raw: string): string[] {
  return (raw || '')
    .split(/[,;]/)
    .map((s) => s.trim())
    .filter((s) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s));
}

function transporterFor(settings: Settings) {
  return nodemailer.createTransport({
    host: settings.smtp_host,
    port: settings.smtp_port,
    // Port 465 is implicit TLS by definition; the toggle is the manual override
    // for the rarer setups (e.g. STARTTLS on a custom port).
    secure: settings.smtp_secure || settings.smtp_port === 465,
    auth: settings.smtp_user ? { user: settings.smtp_user, pass: settings.smtp_password } : undefined,
    // On-prem school mail servers often use self-signed certificates; opt-in
    // via Settings so the default stays strict.
    ...(settings.smtp_allow_self_signed ? { tls: { rejectUnauthorized: false } } : {}),
  });
}

/** Emails the current report with its PDF attached. */
export async function sendReportEmail(report: ReportData, settings: Settings): Promise<EmailResult> {
  const recipients = parseRecipients(settings.email_recipient);
  if (!recipients.length) {
    return { ok: false, error: 'No report recipient configured — add one in Settings.' };
  }
  const from = settings.email_from || settings.smtp_user;
  if (!settings.smtp_host) return { ok: false, error: 'SMTP server not configured — add one in Settings.' };
  if (!from) return { ok: false, error: 'SMTP username / sender address not configured.' };

  try {
    // Reuse the same hidden-window PDF generator as the Export PDF button so
    // the attachment is byte-identical to what the admin saves to disk.
    const pdf = await exportReportToPdf(report);
    const generated = new Date(report.generatedAt).toLocaleString();
    await transporterFor(settings).sendMail({
      from,
      to: recipients.join(', '),
      subject: `Attendance report ${report.from} to ${report.to} — ${report.schoolName}`,
      text: [
        `Please find attached the attendance report for ${report.from} to ${report.to}.`,
        '',
        `Summary: ${report.summary.scans} scans (${report.summary.in} IN / ${report.summary.out} OUT),`,
        `${report.summary.late} late, ${report.summary.early} early, ${report.summary.absent} absent records.`,
        '',
        `Generated by ${report.schoolName} — TapIn School on ${generated}.`,
      ].join('\n'),
      attachments: [
        {
          filename: `tapin-report-${report.from}-to-${report.to}.pdf`,
          content: pdf,
        },
      ],
    });
    return { ok: true, message: `Report emailed to ${recipients.join(', ')}` };
  } catch (err) {
    return { ok: false, error: (err as Error).message };
  }
}

/** Sends a plain test message so the admin can verify the SMTP settings. */
export async function sendTestEmail(to: string, settings: Settings): Promise<EmailResult> {
  if (!settings.smtp_host) return { ok: false, error: 'SMTP server not configured — add one in Settings.' };
  const from = settings.email_from || settings.smtp_user;
  if (!from) return { ok: false, error: 'SMTP username / sender address not configured.' };
  try {
    await transporterFor(settings).sendMail({
      from,
      to,
      subject: `Test email — ${settings.school_name}`,
      text: `This is a test email from ${settings.school_name} (TapIn School). If you can read this, the SMTP settings work.`,
    });
    return { ok: true, message: `Test email sent to ${to}` };
  } catch (err) {
    return { ok: false, error: (err as Error).message };
  }
}
