// Email delivery for the attendance report (P1 6.1). Sends the report PDF as
// an attachment through the school's own SMTP server (Gmail app password,
// Office 365, or any on-prem mail server). Pure-JS nodemailer — no native
// modules, so it runs in the Electron main process and packages cleanly.
import nodemailer from 'nodemailer';
import type { Settings } from '../../shared/types';
import type { AdviserSendDetail, AdviserSendResult, ReportData, EmailResult } from '../../shared/types';
import { exportReportToPdf } from './report-pdf';
import { getReportData } from './report';
import { db } from '../db/connection';

function parseRecipients(raw: string): string[] {
  return (raw || '')
    .split(/[,;]/)
    .map((s) => s.trim())
    .filter((s) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s));
}

function transporterFor(settings: Settings) {
  return nodemailer.createTransport({
    host: settings.smtp_host,
    port: settings.smtp_port,
    // Port 465 is implicit TLS by definition; the toggle is the manual override
    // for the rarer setups (e.g. STARTTLS on a custom port).
    secure: settings.smtp_secure || settings.smtp_port === 465,
    auth: settings.smtp_user ? { user: settings.smtp_user, pass: settings.smtp_password } : undefined,
    // On-prem school mail servers often use self-signed certificates; opt-in
    // via Settings so the default stays strict.
    ...(settings.smtp_allow_self_signed ? { tls: { rejectUnauthorized: false } } : {}),
  });
}

/** Emails the current report with its PDF attached. */
export async function sendReportEmail(report: ReportData, settings: Settings): Promise<EmailResult> {
  const recipients = parseRecipients(settings.email_recipient);
  if (!recipients.length) {
    return { ok: false, error: 'No report recipient configured — add one in Settings.' };
  }
  const from = settings.email_from || settings.smtp_user;
  if (!settings.smtp_host) return { ok: false, error: 'SMTP server not configured — add one in Settings.' };
  if (!from) return { ok: false, error: 'SMTP username / sender address not configured.' };

  try {
    // Reuse the same hidden-window PDF generator as the Export PDF button so
    // the attachment is byte-identical to what the admin saves to disk.
    const pdf = await exportReportToPdf(report);
    const generated = new Date(report.generatedAt).toLocaleString();
    await transporterFor(settings).sendMail({
      from,
      to: recipients.join(', '),
      subject: `Attendance report ${report.from} to ${report.to} — ${report.schoolName}`,
      text: [
        `Please find attached the attendance report for ${report.from} to ${report.to}.`,
        '',
        `Summary: ${report.summary.scans} scans (${report.summary.in} IN / ${report.summary.out} OUT),`,
        `${report.summary.late} late, ${report.summary.early} early, ${report.summary.absent} absent records.`,
        '',
        `Generated by ${report.schoolName} — TapIn School on ${generated}.`,
      ].join('\n'),
      attachments: [
        {
          filename: `tapin-report-${report.from}-to-${report.to}.pdf`,
          content: pdf,
        },
      ],
    });
    return { ok: true, message: `Report emailed to ${recipients.join(', ')}` };
  } catch (err) {
    return { ok: false, error: (err as Error).message };
  }
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/** Strips characters that are unsafe in an email attachment filename. */
function safeFilenamePart(s: string): string {
  return s.replace(/[\\/:*?"<>|]+/g, '-').trim();
}

/**
 * Emails each section adviser a per-student attendance report for their own
 * section (Reports → "Send to advisers"). One email per adviser, each with a
 * PDF generated from the same data source as the on-screen per-student report.
 */
export async function sendAdviserReportEmails(
  from: string,
  to: string,
  settings: Settings,
  schoolYear?: string,
): Promise<AdviserSendResult> {
  const empty = (message: string): AdviserSendResult => ({
    ok: false,
    message,
    sent: 0,
    skipped: 0,
    failed: 0,
    details: [],
  });
  const rows = await db.query<{ grade_section: string; adviser_name: string; email: string }[]>(
    `SELECT grade_section, adviser_name, email FROM sections WHERE email <> '' ORDER BY grade_section`,
  );
  const advisers = rows.filter((r) => EMAIL_RE.test(r.email));
  const skipped = rows.length - advisers.length;
  if (!advisers.length) {
    return empty(
      skipped > 0
        ? 'No advisers have a valid email address — check the Sections tab.'
        : 'No advisers configured yet — add section advisers (with emails) in the Sections tab.',
    );
  }
  const fromAddr = settings.email_from || settings.smtp_user;
  if (!settings.smtp_host) return empty('SMTP server not configured — add one in Settings.');
  if (!fromAddr) return empty('SMTP username / sender address not configured.');

  const transporter = transporterFor(settings);
  const details: AdviserSendDetail[] = [];
  let sent = 0;
  let failed = 0;
  for (const a of advisers) {
    try {
      // Fresh per-section report so each adviser gets exactly their section's
      // per-student summary (phones unmasked so they can follow up with parents).
      // The section groupings reflect the selected school year's enrollments.
      const report = await getReportData({ from, to, type: 'per-student', section: a.grade_section, maskPhones: false, schoolYear });
      const pdf = await exportReportToPdf(report);
      const rate = report.summary.attendanceRate;
      await transporter.sendMail({
        from: fromAddr,
        to: a.email,
        subject: `Attendance report — ${a.grade_section} (${report.from} to ${report.to})`,
        text: [
          `${a.adviser_name ? `Dear ${a.adviser_name}` : 'Dear Adviser'},`,
          '',
          `Please find attached the per-student attendance report for ${a.grade_section} covering ${report.from} to ${report.to}.`,
          '',
          `Summary: ${report.summary.scans} scans (${report.summary.in} IN / ${report.summary.out} OUT), ` +
            `${report.summary.late} late, ${report.summary.absent} absent records. ` +
            `Attendance rate: ${rate === null ? '—' : `${rate.toFixed(1)}%`}.`,
          '',
          `Generated by ${report.schoolName} — TapIn School.`,
        ].join('\n'),
        attachments: [
          {
            filename: `tapin-attendance-${safeFilenamePart(a.grade_section)}-${report.from}-to-${report.to}.pdf`,
            content: pdf,
          },
        ],
      });
      sent++;
      details.push({
        gradeSection: a.grade_section,
        adviserName: a.adviser_name,
        email: a.email,
        ok: true,
        detail: `Sent to ${a.email}`,
      });
    } catch (err) {
      failed++;
      details.push({
        gradeSection: a.grade_section,
        adviserName: a.adviser_name,
        email: a.email,
        ok: false,
        detail: (err as Error).message,
      });
    }
  }
  return {
    ok: failed === 0,
    message:
      `Reports emailed to ${sent} adviser${sent === 1 ? '' : 's'}` +
      `${skipped ? `; ${skipped} skipped (no valid email)` : ''}` +
      `${failed ? `; ${failed} failed` : ''}.`,
    sent,
    skipped,
    failed,
    details,
  };
}

/** Sends a plain test message so the admin can verify the SMTP settings. */
export async function sendTestEmail(to: string, settings: Settings): Promise<EmailResult> {
  if (!settings.smtp_host) return { ok: false, error: 'SMTP server not configured — add one in Settings.' };
  const from = settings.email_from || settings.smtp_user;
  if (!from) return { ok: false, error: 'SMTP username / sender address not configured.' };
  try {
    await transporterFor(settings).sendMail({
      from,
      to,
      subject: `Test email — ${settings.school_name}`,
      text: `This is a test email from ${settings.school_name} (TapIn School). If you can read this, the SMTP settings work.`,
    });
    return { ok: true, message: `Test email sent to ${to}` };
  } catch (err) {
    return { ok: false, error: (err as Error).message };
  }
}
